# Change these first
owner: pay4me # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Pay4Me App Website
    url: https://pay4me.app
  - name: Pay4Me App API
    url: https://api.pay4me.app
  - name: Pay4Me App Console
    url: https://console.pay4me.app
  - name: Pay4Me Pay
    url: https://pay.pay4me.app
  - name: Pay4Me Campaigns
    url: https://campaigns.pay4me.app

status-website:
  cname: status.pay4me.app
  name: Pay4Me
  logoUrl: https://play-lh.googleusercontent.com/_CLu2sfI6RkyNRanybQSjlxjlUj9jJxiR3lJ1Xi_T8-VS6xn1jy2sGd3p_kfpkNuQHk=s96-rw
  favicon: https://play-lh.googleusercontent.com/_CLu2sfI6RkyNRanybQSjlxjlUj9jJxiR3lJ1Xi_T8-VS6xn1jy2sGd3p_kfpkNuQHk=s96-rw
  theme: light
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
