owner: pay4me 
repo: upptime 

sites:
  - name: Website
    url: https://pay4me.app
  - name: Mobile App 
    url: https://api.pay4me.app
  - name: Console 
    url: https://console.pay4me.app
  - name: Queue 
    check: "tcp-ping"
    url: 104.248.226.64

status-website:
  cname: status.pay4me.app
  name: Pay4Me
  logoUrl: https://play-lh.googleusercontent.com/_CLu2sfI6RkyNRanybQSjlxjlUj9jJxiR3lJ1Xi_T8-VS6xn1jy2sGd3p_kfpkNuQHk=s96-rw
  favicon: https://play-lh.googleusercontent.com/_CLu2sfI6RkyNRanybQSjlxjlUj9jJxiR3lJ1Xi_T8-VS6xn1jy2sGd3p_kfpkNuQHk=s96-rw
  theme: night
  navbar:
    - title: Status
      href: /
  i18n:
    footer: Powered by [Pay4Me App](https://pay4me.app)
    
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
