owner: pay4me 
repo: upptime 

sites:
  - name: Pay4Me App Website
    url: https://pay4me.app
  - name: Pay4Me App API
    url: https://api.pay4me.app
  - name: Pay4Me App Console
    url: https://console.pay4me.app
  - name: Pay4Me Pay
    url: https://pay.pay4me.app
  - name: Pay4Me Campaigns
    url: https://campaigns.pay4me.app

status-website:
  cname: status.pay4me.app
  name: Pay4Me
  logoUrl: https://play-lh.googleusercontent.com/_CLu2sfI6RkyNRanybQSjlxjlUj9jJxiR3lJ1Xi_T8-VS6xn1jy2sGd3p_kfpkNuQHk=s96-rw
  favicon: https://play-lh.googleusercontent.com/_CLu2sfI6RkyNRanybQSjlxjlUj9jJxiR3lJ1Xi_T8-VS6xn1jy2sGd3p_kfpkNuQHk=s96-rw
  theme: dark
  navbar:
    - title: Status
      href: /
  i18n:
    footer: Powered by [Pay4Me App](https://pay4me.app)
    
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
